include cflags.mk
OUTDIR?=.
CC=gcc
CFLAGS=$(CFLAGS_COMMON) -fPIC -DPIC
AR=ar
RM=/bin/rm

.PHONY: all
all: $(OUTDIR)/liblppreload.so

# Append -DENABLE_LARGE_CODE_PAGES=1 to CFLAGS on supported platforms.
include ../detect-platform.mk

%.o: %.c
	$(CC) $(CFLAGS) -x c -c $< -o $@

OBJECTS=\
  large_page.o \
  lp_preload.o \

$(OUTDIR)/liblppreload.so: $(OBJECTS)
	$(CC) -shared -o $@ $(OBJECTS)

.PHONY: clean
clean:
	$(RM) -f *.o $(OUTDIR)/*.a
