# Copyright (C) 2021 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT
version: "3.3"
services:
  wp4.2_php7.4_base_querycacheoff_http:
    build: 
      context: ./wp_base/http
      dockerfile: Dockerfile
    image: wp4.2_php7.4_base_querycacheoff_http
  wp4.2_php7.4_base_querycacheoff_https:
    build:
      context: ./wp_base/https
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_base_querycacheoff_http
    image: wp4.2_php7.4_base_querycacheoff_https
  wp4.2_php7.4_opt_querycacheon_http:
    build:
      context: ./wp_opt/http
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_base_querycacheoff_http
    image: wp4.2_php7.4_opt_querycacheon_http
  wp4.2_php7.4_opt_querycacheon_with_https:
    build:
      context: ./wp_base/https
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_opt_querycacheon_http
    image: wp4.2_php7.4_opt_querycacheon_with_https
  wp4.2_php7.4_opt_querycache_on_https_opt:
    build:
      context: ./wp_opt/https
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_opt_querycacheon_with_https
    image: wp4.2_php7.4_opt_querycacheon_https_opt
  wp4.2_php7.4_opt_querycacheoff_1_instance_only_http:
    build:
      context: ./wp_opt/http
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_base_querycacheoff_http
          mariadbconf: 2s
    image: wp4.2_php7.4_opt_querycacheoff_1_instance_only_http
  wp5.2_php7.4_base_querycacheoff_http:
    build: 
      context: ./wp5.2_base/http
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_base_querycacheoff_http
    image: wp5.2_php7.4_base_querycacheoff_http
  wp5.2_php7.4_opt_querycacheon_http:
    build: 
      context: ./wp5.2_opt/http
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_opt_querycacheon_http
    image: wp5.2_php7.4_opt_querycacheon_http
  wp5.2_php7.4_opt_querycacheoff_1_instance_only_http:
    build: 
      context: ./wp5.2_opt/http
      dockerfile: Dockerfile
      args:
          baseimage: wp4.2_php7.4_opt_querycacheoff_1_instance_only_http
    image: wp5.2_php7.4_opt_querycacheoff_1_instance_only_http
