#!/bin/bash

# Copyright (C) 2018 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

SCRIPTS_DIR=`dirname $0`
source ${SCRIPTS_DIR}/utils.sh

function help_l2_demand_code_MPI() {
	echo "      Measure cache code read (fetch) misses per-instruction."
}

function init_l2_demand_code_MPI() {
  local local_pmu_array=(instructions l2_rqsts.code_rd_miss)
  for item in ${local_pmu_array[*]}
  do
    if [ "x${local_pmus}" == "x" ]; then
      local_pmus="$item"
    else
      local_pmus="$local_pmus,$item"
    fi
  done
  echo $local_pmus
}

function calc_l2_demand_code_MPI() {
  local perf_data_file="$1"
  echo
  echo "================================================="
  echo "Final L2_demand_code MPI metric"
  echo "--------------------------------------------------"
  echo "FORMULA: metric_L2_demand_code_MPI = (a/b)"
  echo "         where, a=l2_rqsts.code_rd_miss"
  echo "                b=instructions"
  echo "================================================="

  local a=`return_pmu_value "l2_rqsts.code_rd_miss" $perf_data_file `
  local b=`return_pmu_value "instructions" $perf_data_file`
  if [ $a == -1 -o $b == -1 ]; then
    echo "ERROR: metric_L2_demand_code_MPI can't be derived. Missing pmus"
  else
    local metric=`echo "scale=$bc_scale;(${a}/${b})"| bc -l`
    echo "metric_L2_demand_code_MPI=${metric}"
  fi

  echo
}
